name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
   IMAGE_TAG: ${{ github.run_number }}
   DOCKER_REPOSITORY: katetselishchava
   IMAGE_NAME: webapp
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build ./app-dotnet --file ./app-dotnet/Dockerfile --tag webapp:$IMAGE_TAG
    - name: Tag the Docker image
      run: docker tag webapp:$IMAGE_TAG $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
    - name: Login to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_REPOSITORY_PASSWORD }}" | docker login -u $DOCKER_REPOSITORY --password-stdin
    - name: Push Image to Docker Hub
      run:
        docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$IMAGE_TAG
    - name: Azure Kubernetes set context
      uses: Azure/aks-set-context@v1
      with:
        creds: ${{ secrets.AZURE_SUBSCRIPTION_SPN }}
        # Resource Group Name
        resource-group: refinitiv-sample-kt-aks
        # AKS Cluster Name
        cluster-name: refinitiv-sample-kt-cluster
    - name: Deploy to Kubernetes cluster
      uses: Azure/k8s-deploy@v1.3
      with:
        # Choose the target Kubernetes namespace. If the namespace is not provided, the commands will run in the default namespace.
        namespace: katetselishchava
        # Path to the manifest files which will be used for deployment.
        manifests: |
          02_kubernetes_aks/app-deploy.yaml
          02_kubernetes_aks/configmap.yaml
          02_kubernetes_aks/db-deploy.yaml
          02_kubernetes_aks/disk-pvc.yaml
